import random
import string

print("Hello, welcome to the password generator!")

lenght = int(input('\nEnter a lenght of the password please:\n'))


upp = string.ascii_uppercase
lwr = string.ascii_lowercase
num = string.digits
sym = string.punctuation

all = upp + lwr + num + sym

temp = random.sample(all, lenght)

wachtwoord = "".join(temp)

print(wachtwoord)


anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()

anws = input('Would you like to make a new password? (Yes, No)\n')
if anws == 'Yes':
    lenght = int(input('\nEnter a lenght of the password please:\n'))


    upp = string.ascii_uppercase
    lwr = string.ascii_lowercase
    num = string.digits
    sym = string.punctuation

    all = upp + lwr + num + sym

    temp = random.sample(all, lenght)

    wachtwoord = "".join(temp)

    print(wachtwoord)

if anws == 'No':
    exit()